// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterName string                 `protobuf:"bytes,1,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetX       int32                  `protobuf:"varint,1,opt,name=target_x,json=targetX,proto3" json:"target_x,omitempty"`
	TargetY       int32                  `protobuf:"varint,2,opt,name=target_y,json=targetY,proto3" json:"target_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *MoveRequest) GetTargetX() int32 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *MoveRequest) GetTargetY() int32 {
	if x != nil {
		return x.TargetY
	}
	return 0
}

type PathNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathNode) Reset() {
	*x = PathNode{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathNode) ProtoMessage() {}

func (x *PathNode) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathNode.ProtoReflect.Descriptor instead.
func (*PathNode) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *PathNode) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PathNode) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MoveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	X              int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y              int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	ActionPoints   int32                  `protobuf:"varint,4,opt,name=action_points,json=actionPoints,proto3" json:"action_points,omitempty"`
	MovementPoints int32                  `protobuf:"varint,5,opt,name=movement_points,json=movementPoints,proto3" json:"movement_points,omitempty"`
	Path           []*PathNode            `protobuf:"bytes,6,rep,name=path,proto3" json:"path,omitempty"`
	PathCost       int32                  `protobuf:"varint,7,opt,name=path_cost,json=pathCost,proto3" json:"path_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveResponse) GetActionPoints() int32 {
	if x != nil {
		return x.ActionPoints
	}
	return 0
}

func (x *MoveResponse) GetMovementPoints() int32 {
	if x != nil {
		return x.MovementPoints
	}
	return 0
}

func (x *MoveResponse) GetPath() []*PathNode {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *MoveResponse) GetPathCost() int32 {
	if x != nil {
		return x.PathCost
	}
	return 0
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*GameEvent_PlayerConnected
	//	*GameEvent_PlayerDisconnected
	//	*GameEvent_PlayerMoved
	//	*GameEvent_ChatMessage
	//	*GameEvent_MapData
	//	*GameEvent_CombatStart
	Event         isGameEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameEvent) GetEvent() isGameEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GameEvent) GetPlayerConnected() *PlayerConnected {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerConnected); ok {
			return x.PlayerConnected
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerDisconnected() *PlayerDisconnected {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerDisconnected); ok {
			return x.PlayerDisconnected
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerMoved() *PlayerMoved {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerMoved); ok {
			return x.PlayerMoved
		}
	}
	return nil
}

func (x *GameEvent) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *GameEvent) GetMapData() *MapData {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_MapData); ok {
			return x.MapData
		}
	}
	return nil
}

func (x *GameEvent) GetCombatStart() *CombatStart {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_CombatStart); ok {
			return x.CombatStart
		}
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_PlayerConnected struct {
	PlayerConnected *PlayerConnected `protobuf:"bytes,1,opt,name=player_connected,json=playerConnected,proto3,oneof"`
}

type GameEvent_PlayerDisconnected struct {
	PlayerDisconnected *PlayerDisconnected `protobuf:"bytes,2,opt,name=player_disconnected,json=playerDisconnected,proto3,oneof"`
}

type GameEvent_PlayerMoved struct {
	PlayerMoved *PlayerMoved `protobuf:"bytes,3,opt,name=player_moved,json=playerMoved,proto3,oneof"`
}

type GameEvent_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,4,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type GameEvent_MapData struct {
	MapData *MapData `protobuf:"bytes,5,opt,name=map_data,json=mapData,proto3,oneof"`
}

type GameEvent_CombatStart struct {
	CombatStart *CombatStart `protobuf:"bytes,6,opt,name=combat_start,json=combatStart,proto3,oneof"`
}

func (*GameEvent_PlayerConnected) isGameEvent_Event() {}

func (*GameEvent_PlayerDisconnected) isGameEvent_Event() {}

func (*GameEvent_PlayerMoved) isGameEvent_Event() {}

func (*GameEvent_ChatMessage) isGameEvent_Event() {}

func (*GameEvent_MapData) isGameEvent_Event() {}

func (*GameEvent_CombatStart) isGameEvent_Event() {}

type PlayerConnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerConnected) Reset() {
	*x = PlayerConnected{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerConnected) ProtoMessage() {}

func (x *PlayerConnected) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerConnected.ProtoReflect.Descriptor instead.
func (*PlayerConnected) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerConnected) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerConnected) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerConnected) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerConnected) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDisconnected) Reset() {
	*x = PlayerDisconnected{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnected) ProtoMessage() {}

func (x *PlayerDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnected.ProtoReflect.Descriptor instead.
func (*PlayerDisconnected) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerDisconnected) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerMoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Path          []*PathNode            `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMoved) Reset() {
	*x = PlayerMoved{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoved) ProtoMessage() {}

func (x *PlayerMoved) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoved.ProtoReflect.Descriptor instead.
func (*PlayerMoved) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerMoved) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerMoved) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMoved) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMoved) GetPath() []*PathNode {
	if x != nil {
		return x.Path
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Cells         []*MapCell             `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *MapData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapData) GetCells() []*MapCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type MapCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	TerrainType   int32                  `protobuf:"varint,3,opt,name=terrain_type,json=terrainType,proto3" json:"terrain_type,omitempty"`
	Walkable      bool                   `protobuf:"varint,4,opt,name=walkable,proto3" json:"walkable,omitempty"`
	Elevation     int32                  `protobuf:"varint,5,opt,name=elevation,proto3" json:"elevation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapCell) Reset() {
	*x = MapCell{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapCell) ProtoMessage() {}

func (x *MapCell) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapCell.ProtoReflect.Descriptor instead.
func (*MapCell) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *MapCell) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapCell) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapCell) GetTerrainType() int32 {
	if x != nil {
		return x.TerrainType
	}
	return 0
}

func (x *MapCell) GetWalkable() bool {
	if x != nil {
		return x.Walkable
	}
	return false
}

func (x *MapCell) GetElevation() int32 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

type CombatStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	Players       []*CombatPlayer        `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatStart) Reset() {
	*x = CombatStart{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStart) ProtoMessage() {}

func (x *CombatStart) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStart.ProtoReflect.Descriptor instead.
func (*CombatStart) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *CombatStart) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *CombatStart) GetPlayers() []*CombatPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type CombatPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Team          int32                  `protobuf:"varint,3,opt,name=team,proto3" json:"team,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatPlayer) Reset() {
	*x = CombatPlayer{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatPlayer) ProtoMessage() {}

func (x *CombatPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatPlayer.ProtoReflect.Descriptor instead.
func (*CombatPlayer) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *CombatPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CombatPlayer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CombatPlayer) GetTeam() int32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *CombatPlayer) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CombatPlayer) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\x1a\x1bgoogle/protobuf/empty.proto\"7\n" +
	"\x0eConnectRequest\x12%\n" +
	"\x0echaracter_name\x18\x01 \x01(\tR\rcharacterName\"C\n" +
	"\vMoveRequest\x12\x19\n" +
	"\btarget_x\x18\x01 \x01(\x05R\atargetX\x12\x19\n" +
	"\btarget_y\x18\x02 \x01(\x05R\atargetY\"&\n" +
	"\bPathNode\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xd3\x01\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12#\n" +
	"\raction_points\x18\x04 \x01(\x05R\factionPoints\x12'\n" +
	"\x0fmovement_points\x18\x05 \x01(\x05R\x0emovementPoints\x12\"\n" +
	"\x04path\x18\x06 \x03(\v2\x0e.game.PathNodeR\x04path\x12\x1b\n" +
	"\tpath_cost\x18\a \x01(\x05R\bpathCost\"'\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf9\x02\n" +
	"\tGameEvent\x12B\n" +
	"\x10player_connected\x18\x01 \x01(\v2\x15.game.PlayerConnectedH\x00R\x0fplayerConnected\x12K\n" +
	"\x13player_disconnected\x18\x02 \x01(\v2\x18.game.PlayerDisconnectedH\x00R\x12playerDisconnected\x126\n" +
	"\fplayer_moved\x18\x03 \x01(\v2\x11.game.PlayerMovedH\x00R\vplayerMoved\x126\n" +
	"\fchat_message\x18\x04 \x01(\v2\x11.game.ChatMessageH\x00R\vchatMessage\x12*\n" +
	"\bmap_data\x18\x05 \x01(\v2\r.game.MapDataH\x00R\amapData\x126\n" +
	"\fcombat_start\x18\x06 \x01(\v2\x11.game.CombatStartH\x00R\vcombatStartB\a\n" +
	"\x05event\"f\n" +
	"\x0fPlayerConnected\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\"1\n" +
	"\x12PlayerDisconnected\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"j\n" +
	"\vPlayerMoved\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\"\n" +
	"\x04path\x18\x04 \x03(\v2\x0e.game.PathNodeR\x04path\"`\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\\\n" +
	"\aMapData\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12#\n" +
	"\x05cells\x18\x03 \x03(\v2\r.game.MapCellR\x05cells\"\x82\x01\n" +
	"\aMapCell\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12!\n" +
	"\fterrain_type\x18\x03 \x01(\x05R\vterrainType\x12\x1a\n" +
	"\bwalkable\x18\x04 \x01(\bR\bwalkable\x12\x1c\n" +
	"\televation\x18\x05 \x01(\x05R\televation\"X\n" +
	"\vCombatStart\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12,\n" +
	"\aplayers\x18\x02 \x03(\v2\x12.game.CombatPlayerR\aplayers\"w\n" +
	"\fCombatPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04team\x18\x03 \x01(\x05R\x04team\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y2\xa3\x01\n" +
	"\vGameService\x122\n" +
	"\aConnect\x12\x14.game.ConnectRequest\x1a\x0f.game.GameEvent0\x01\x12-\n" +
	"\x04Move\x12\x11.game.MoveRequest\x1a\x12.game.MoveResponse\x121\n" +
	"\x04Chat\x12\x11.game.ChatRequest\x1a\x16.google.protobuf.EmptyB\x19Z\x17mmorpg/server/api/protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_proto_goTypes = []any{
	(*ConnectRequest)(nil),     // 0: game.ConnectRequest
	(*MoveRequest)(nil),        // 1: game.MoveRequest
	(*PathNode)(nil),           // 2: game.PathNode
	(*MoveResponse)(nil),       // 3: game.MoveResponse
	(*ChatRequest)(nil),        // 4: game.ChatRequest
	(*GameEvent)(nil),          // 5: game.GameEvent
	(*PlayerConnected)(nil),    // 6: game.PlayerConnected
	(*PlayerDisconnected)(nil), // 7: game.PlayerDisconnected
	(*PlayerMoved)(nil),        // 8: game.PlayerMoved
	(*ChatMessage)(nil),        // 9: game.ChatMessage
	(*MapData)(nil),            // 10: game.MapData
	(*MapCell)(nil),            // 11: game.MapCell
	(*CombatStart)(nil),        // 12: game.CombatStart
	(*CombatPlayer)(nil),       // 13: game.CombatPlayer
	(*emptypb.Empty)(nil),      // 14: google.protobuf.Empty
}
var file_game_proto_depIdxs = []int32{
	2,  // 0: game.MoveResponse.path:type_name -> game.PathNode
	6,  // 1: game.GameEvent.player_connected:type_name -> game.PlayerConnected
	7,  // 2: game.GameEvent.player_disconnected:type_name -> game.PlayerDisconnected
	8,  // 3: game.GameEvent.player_moved:type_name -> game.PlayerMoved
	9,  // 4: game.GameEvent.chat_message:type_name -> game.ChatMessage
	10, // 5: game.GameEvent.map_data:type_name -> game.MapData
	12, // 6: game.GameEvent.combat_start:type_name -> game.CombatStart
	2,  // 7: game.PlayerMoved.path:type_name -> game.PathNode
	11, // 8: game.MapData.cells:type_name -> game.MapCell
	13, // 9: game.CombatStart.players:type_name -> game.CombatPlayer
	0,  // 10: game.GameService.Connect:input_type -> game.ConnectRequest
	1,  // 11: game.GameService.Move:input_type -> game.MoveRequest
	4,  // 12: game.GameService.Chat:input_type -> game.ChatRequest
	5,  // 13: game.GameService.Connect:output_type -> game.GameEvent
	3,  // 14: game.GameService.Move:output_type -> game.MoveResponse
	14, // 15: game.GameService.Chat:output_type -> google.protobuf.Empty
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[5].OneofWrappers = []any{
		(*GameEvent_PlayerConnected)(nil),
		(*GameEvent_PlayerDisconnected)(nil),
		(*GameEvent_PlayerMoved)(nil),
		(*GameEvent_ChatMessage)(nil),
		(*GameEvent_MapData)(nil),
		(*GameEvent_CombatStart)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
